version: '3.8'
services:
  mariadb:
    image: mariadb:11-alpine
    container_name: solar-mariadb
    command: --bind-address=0.0.0.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=solar123
      - MYSQL_DATABASE=solartracker
      - MYSQL_USER=solar
      - MYSQL_PASSWORD=solar123
    volumes:
      - /volume1/docker/solar-tracker/mariadb:/var/lib/mysql
  
  solar-tracker:
    image: ghcr.io/efmaster/solar-tracker:latest
    container_name: solartracker
    restart: unless-stopped
    depends_on:
      - mariadb
    
    ports:
      - "3117:3000"
    volumes:
      - /volume1/docker/solar-tracker:/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://solar:solar123@mariadb:3306/solartracker